### ISSUE TITLE
Add keybindings for run etc.

### ISSUE THREAD

**Issue by magnus-madsen** [flix/vscode-flix#109]
https://code.visualstudio.com/api/references/contribution-points#contributes.keybindings

- What keybindings do we even want?
- Like what commands?
- And what key should they be bound to.

We could look at the Java/Scala or other plugins to see what keybindings they use

**Comment by magnus-madsen** [comment]
@manoj2601 I would ask you to create a table with suggestions for keybindings (inspired by what other extensions use) and then we can discuss it before implementing anything.

**Comment by manoj2601** [comment]
Although there are not many keybindings in java, scala, C++ or Python which can be used in flix. No keybindings are defined for run etc. in these languages. There are keybindings that are VSCode specific such as restart project, a comment line, etc. These keybindings work in the Flix plugin as well without adding manually. However, I am noting down some suggestions which can be useful for flix: 

- [ ] flix.internalRestart : Ctrl + Alt + F2, Cmd + Alt + F2 
- [ ] flix.cmdRunProject : Ctrl + F2, Cmd + F2
- [ ] flix.runMain : Ctrl + Alt + R, Cmd + Alt + R 
- [ ] flix.runMainWithArgs : Ctrl + Alt + A, Cmd + Alt + A 
- [ ] flix.cmdCheck : Ctrl + Alt + C, Cmd + Alt + C 
- [ ] flix.cmdBuild : Ctrl + Alt + B, Cmd + Alt + B 
- [ ] flix.cmdBuildJar : Ctrl + Alt + J, Cmd + Alt + J 
- [ ] flix.cmdBuildPkg : Ctrl + Alt + P, Cmd + Alt + P 
- [ ] flix.cmdTests : Ctrl + Alt + T, Cmd + Alt + T

Please let me know which keybinding could be convenient for users so that we only add them.

**Comment by magnus-madsen** [comment]
Added a few keybindings.
