### ISSUE TITLE
Update language-configuration.json

### ISSUE THREAD

**Issue by magnus-madsen** [flix/vscode-flix#124]
See https://code.visualstudio.com/api/language-extensions/language-configuration-guide

**Comment by magnus-madsen** [comment]
@manoj2601 If you could inspect these options and determine if there are some we are missing.

**Comment by manoj2601** [comment]
Some points to note:
1. block comment `["/*", "*/"]`
2. autoClosingPair for block comment `["/**", "*/"]` i.e. if user types "/*" and then one one "*", it will autoclose with "*/".
3. can we do something for "Folding"? the editors default folding strategy seems fine. (indentation based folding strategy). Java extension also removed the region folding in their latest update. So I think the existing default folding is fine.
4. indentationRules are not really required since we have already defined snippets.
