### ISSUE TITLE
Syntax coloring of arrays

### ISSUE THREAD

**Issue by magnus-madsen** [flix/vscode-flix#171]
Is this right?:

![image](https://user-images.githubusercontent.com/2287953/142725349-8634d292-e0b2-4510-8e9b-bdfc3ed48c7e.png)

**Comment by jhckragh** [comment]
I don't think it's right. I think the elements of an array literal should be highlighted individually. 🙂

In the posted example it seems the presence of the cast causes an extra semantic token to appear that covers the whole array literal. With the following similar code,

```
def main(_: Array[String]): Int32 & Impure =
    let s = Some([1, 2, 3] as & Pure);
    println(s);
    0
```

the semantic tokens response is:

```
[0:4] 'main' (FUNCTION)
[0:9] '_: Array[String]' (PARAMETER)
[0:12] 'Array' (TYPE)
[0:18] 'String' (TYPE)
[0:28] 'Int32' (TYPE)
[1:8] 's' (VARIABLE)
[1:12] 'Some' (ENUMMEMBER)
[1:17] '[1, 2, 3]' (TYPE) // (!)
[2:4] 'println' (FUNCTION)
[2:12] 's' (VARIABLE)
```

If the cast is removed, then no token is produced for `[1, 2, 3]`. Maybe there's a case in one of the `visit` methods in the `SemanticTokensProvider` that causes array literals to be visited within casts?

I think it's best not to produce a token that covers a whole array literal, because it will lead to overlapping tokens if any of the array elements themselves are visited. For example, that happens if the declaration of `s` is changed to:

```
let s = Some([Some(1), Some(2), Some(3)] as & Pure);
```

**Comment by magnus-madsen** [comment]
(Array literals will be removed).
