### ISSUE TITLE
Investigate support for "rename file"

### ISSUE THREAD

**Issue by magnus-madsen** [flix/vscode-flix#234]
Renaming a file seems to break the extension. (Possibly because the creation/deletion is not registered correctly?).

**Comment by mR4smussen** [comment]
> Renaming a file seems to break the extension

I want to be sure I’m seeing the same error as you are.
When I rename a file, the compiler throws a "function overload" error for around one second before going back to normal? 
This could be caused by the compiler taking around a second longer to realise that the old file name no longer exists than it takes for the compiler to see that a new file exists (making two identical files exist for a short period)

**Comment by magnus-madsen** [comment]
Oh, so it does go back to normal?

**Comment by mR4smussen** [comment]
Yes, I can rename a .flix file and after a second everything seems to be back to normal.

**Comment by magnus-madsen** [comment]
In that case, I think we can consider this fixed.
